AWSTemplateFormatVersion: 2010-09-09
Description: Outputs Lab - Log to Console

Parameters:
  MyKeyName:
    Description: Select the key name from the list
    Type: AWS::EC2::KeyPair::KeyName

Resources: 
  DevEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-0742b4e673072066f
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - default     
        - !Ref SSHSecurityGroup 
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: my new SSH security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
    
Outputs:
  DevInstanceId:
    Description: My instance id
    Value: !Ref DevEC2Instance
