AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance.

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0742b4e673072066f
      InstanceType: t2.micro
      KeyName: cfn-key-1
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: my new SSH SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
        # New security rule added for demonstration of case sensitivity
        #The IP protocol (I.e. TCP or UDP) for the desired HTTP rule is tcp
        - IpProtocol: tcp
          # Defines the originating port allowed by the ingress rule - in thss case port 8081
          FromPort: '8081'
          # Defines the destination port allowed by the ingress rule - in thss case port 8081
          ToPort: '8081'
          # Defition intentionally has an incorrect case of IP instead of Ip to experience a 
          # CloudFormation case sensivity error
          # Defines the allowed source IP address range allowed via this security group rule.
          # In this case - all traffic is allowed via the wildcard network CIDR specification.
          CidrIP: 0.0.0.0/0          

  MyElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref DevEC2Instance           